@startuml
Title UaaS Deployment
' left to right direction


actor user
cloud PeerNode

package Service {
    () "REST_API"
    component "WebService\n(Python)" as WebService

    user <--> REST_API
    REST_API -- WebService

    component "UaaS\n(Rust)" as UaaS

    package DockerContainer_MySQL {
        database MySQL
    }
    UaaS --> MySQL
    WebService <-- MySQL


    PeerNode --> UaaS: P2P Messages
}

@enduml