@startuml
title UaaS Related Projects and Tools

package Complete {
    class UaaS_Python
}

package Current {
    class UaaS_Rust
    class BNAR_Athena
    class Wireshark_BSV
}

BNAR_Athena -up-|> UaaS_Python: inspired_by
UaaS_Rust -up-|> UaaS_Python: inspired_by

package Future {
    class BSV_NOC
    class UaaS_BitBlock_Integration
}

UaaS_Rust -right-> Wireshark_BSV : required
UaaS_BitBlock_Integration -up-|> UaaS_Rust: could_use
BSV_NOC -up-|> BNAR_Athena: could_use
BSV_NOC -up-|> UaaS_Rust: could_use

@enduml
