@startuml
title UaaS Projects and Tools


package Complete {
    class UaaS_Python
}

package Current {
    class BNAR_Athena
    class UaaS_Rust

}

BNAR_Athena -up-|> UaaS_Python: inspired_by
UaaS_Rust -up-|> UaaS_Python: inspired_by


package Future {
    class UaaS_BitBlock_Integration
    class BSV_NOC
    class Wireshark_BSV
}


Wireshark_BSV -up-|> UaaS_Rust : was_required
UaaS_BitBlock_Integration -up-|> UaaS_Rust: uses
BSV_NOC -up-|> BNAR_Athena: uses
BSV_NOC -up-|> UaaS_Rust: uses




@enduml
