[package]
name = "uaas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# if dowloading blocks >32 MB :
sv = { version = "0.2.2", path = "../../rust-sv" }
# else use:
# sv = "0.2.2"
# See README.md for details.

serde = { version = "1.0", features =["derive"] }
toml = "0.5.8"
lazy_static = "1.4.0"
serde_json = "1.0"
mysql = "*"
chrono = "0.4"
rand = "0.8.5"
hex = "0.4.3"
regex = "1"
actix-web = "4"
retry = "1.3.1"